#!/bin/sh
set -e
cd t
n=$(ls -d [0-9]* | awk '$1>max {max=$1} END { printf "%04d", max+1 }' )
cat <<EOF > $n.t
#/bin/sh
. ./t/test.sh
test 'description' 'input' 'output'
EOF
chmod +x $n.t
echo "Created t/$n.t"
